Improve test before release, no push

diff --git a/bin/dosh b/bin/dosh
--- a/bin/dosh
+++ b/bin/dosh
@@ -104,18 +104,17 @@ nextest() {
 }
 
 push() {
-    # We only need to send the binary, not the entire project
-    rsync target/release/neems-core root@newtown.energy:/opt/neems/core
+    echo "Don't push from here.  Use the deploy repo."
 }
 
 release() {
     # Build a release bin
     rustup update
     echo "🚀 Building release version..."
-    local flags="--features fixphrase --features admin-cli"
-    # The test-staging feature just makes sure we run some security tests:w
-    FORCE_TEST_ALL=1 cargo $NIGHTLY test --release $flags --features test-staging "$@" || {
-	echo "❌ Tests failed. Please check the output above."
+    # The test-staging feature just makes sure we run some security tests.
+    local flags="--features fixphrase --features admin-cli --features test-staging"
+    FORCE_TEST_ALL=1 cargo $NIGHTLY test --quiet --release $flags --features test-staging "$@" || {
+	echo "❌ Tests failed. Please check the output above and junit.xml"
 	return 1
     }
     cargo $NIGHTLY build --release $flags "$@" || {
